services:
  - type: web
    name: erg-landing-page
    env: static
    buildCommand: npm ci --only=production && npm run build:prod
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /
    autoDeploy: true 